### PR TITLE
replace cx addons to classnames

### PR DESCRIPTION
**Pull request by wisely0515**
eliminate `React.addons.classSet` deprecated warning

### CODE REVIEW

**Comment by kirkchen** [comment]
Hi, 

Could you please help us resolve conflicts ?
Thanks!

**Comment by dca** [comment]
```
$ git checkout master
$ git pull source master

$ git checkout replace_classnames
$ git rebase -i master
```

應該是像這樣

**Comment by appleboy** [comment]
@dca 合併成一個 command 即可，在此 branch 內下

```
$ git pull --rebase upstream master
```

**Comment by dca** [comment]
@appleboy 喔喔!! 學習了，感謝感謝 :+1:

**Comment by wisely0515** [comment]
感謝大家 :+1:

**Comment by maxchu2021** [comment]
@appleboy 可以寫到 Readme 嗎?

**Pull request merged**
